// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Scryfall.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CardFace
    {
        /// <summary>
        /// Initializes a new instance of the CardFace class.
        /// </summary>
        public CardFace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CardFace class.
        /// </summary>
        public CardFace(string name = default(string), string typeLine = default(string), string oracleText = default(string), string manaCost = default(string), IList<Colors?> colors = default(IList<Colors?>), IList<Colors?> colorIndicator = default(IList<Colors?>), string power = default(string), string toughness = default(string), string loyalty = default(string), string flavorText = default(string), System.Guid? illustrationId = default(System.Guid?), ImageUri imageUris = default(ImageUri))
        {
            Name = name;
            TypeLine = typeLine;
            OracleText = oracleText;
            ManaCost = manaCost;
            Colors = colors;
            ColorIndicator = colorIndicator;
            Power = power;
            Toughness = toughness;
            Loyalty = loyalty;
            FlavorText = flavorText;
            IllustrationId = illustrationId;
            ImageUris = imageUris;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type_line")]
        public string TypeLine { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oracle_text")]
        public string OracleText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mana_cost")]
        public string ManaCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "colors")]
        public IList<Colors?> Colors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "color_indicator")]
        public IList<Colors?> ColorIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "power")]
        public string Power { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toughness")]
        public string Toughness { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "loyalty")]
        public string Loyalty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flavor_text")]
        public string FlavorText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "illustration_id")]
        public System.Guid? IllustrationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_uris")]
        public ImageUri ImageUris { get; set; }

    }
}
